#lost the source of this -- author unknown

apatheme=theme_bw()+
theme(panel.grid.major=element_blank(),
panel.grid.minor=element_blank(),
panel.border=element_blank(),
axis.line=element_line(),
text=element_text(family='Times'),
legend.title=element_blank())
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="white",color="black")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="white",color="black")+apatheme
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill=c("white","black"),color="black")+apatheme
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="blue")+stat_summary(fun.data=mean_cl_normal,geom="errorbar")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="blue")+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.2)
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="blue")+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.1)
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="blue")+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.05)
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill=c("white","gray")+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.05)+apatheme
)
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill=c("white","gray")+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.05)
)
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill=c("white","gray"))+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.05)+apatheme
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill=c("white","gray"),color="black")+stat_summary(fun.data=mean_cl_normal,geom="errorbar",width=.05)+apatheme
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="blue")+stat_summary(fun.data=mean_cl_normal,geom="pointrange")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",color="gray")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",color="white")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",colorFill="white")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",Fill="white")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="white")
ggplot(sentLong,aes(group,scores))+stat_summary(fun.y=mean,geom="bar",fill="white",color="black")
